### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by shimoharuki** [shimoharuki/usj_app#8]

**Comment by kerochelo** [comment]
@shimoharuki 
下記の観点からレビューをいたしました。
```
READMEから課題解決する実装がされているか&動いている
静的コードチェックが入っている
就活において十分な技術力を示せる機能を実装しているか
UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
```

## READMEから課題解決する実装がされているか&動いている
- 先にREADMEのmarkdownが効いてないので、みやすいように修正しておきましょう。
- 機能自体は実装できているので、本リリースではこれに技術的なアピールポイントが増えるような実装を加えていきましょう。

## 静的コードチェックが入っている
rubocopしっかり利用されているようにですね！
最低限のコードのチェックをしているのでこれからも活用していきましょう！

## 就活において十分な技術力を示せる機能を実装しているか
### おすすめの作成するための処理
- application_controller.rbにメソッドを実装していますが、別のcontrollerもしくはmodelに処理を切り出しておきましょう。
  - 命名は`recommend_question_controller`などどんなentityに対してのCRUDなのか考えると良い命名になります
- 質問ごとにページ遷移をせずに1ページ内で全ての質問に答えられるようにUIを修正しましょう。
  - JSなどでSPAっぽく実装できると技術のアピールポイントにもなります！
- AnsewrRecommendationのモデル名がタイポしているので他の実装などで処理が複雑になる前に早めに直しておきましょう。
- first_recommend等の処理内で文字列で記載している箇所は定数などで定義して、その定数と使うようにしましょう（`とにかくアトラクションに乗りたい`、`家族`、`スーパーニンテンドーワールド`など）
- answers_with_choicesのデータを作成する処理はリファクタできるのでChatGPTに投げてみてより簡潔なコードに修正しておきましょう。

### その他
- RSpec等テストを書いておきましょう。まずは、modelからテストを進めていき、メイン機能周りのsystem specを書いていきましょう。
- 情報一覧を出すページなどHotwireを利用してSPAっぽい形に実装しておきましょう（技術的にプラスポイントになる）


## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
- 最初に診断からおすすめの情報を作成してくれると思いますが、作成後はおすすめページに遷移した方がユーザーにとってどんな処理をしたのか分かりやすいので修正しておきましょう。
- マイページや利用規約など背景と文字の色合い的に見にくいかもです、このあたり背景の色合いを修正しておきましょう。
- ヘッダーとフッターのメニューを整理してまとめておきましょう。
  - フッターの方にも頻繁に利用する導線へのリンクがあるので、ヘッダーに移動するといいですね。またヘッダーメニューが多くなるので、プルダウンを使ってまとめたり、表示するメニューをより利用するメニューに厳選するといいですね。下記の記事がとても分かりやすいので参考にしてみてください。
[UIデザインパターン](https://www.sociomedia.co.jp/category/uidesignpatterns)
[ヒューマンインターフェース ガイドライン](https://www.sociomedia.co.jp/category/shig)
- ログイン状態でもTOPページに新規登録やログインの導線があるので、TOPページの内容を修正しておきましょう。
- タグのUIもただの文字ではなく、タグっぽいデザインを適用しておきましょう。
- おすすめページなどフッターに隠れてメインの情報が見えない箇所があるので修正しておきましょう。


上記内容を確認いただき、issueにタスクを書き出したら、本リリースまでに修正や実装を進めていきましょう。
issueに切り出し、やるべき内容をまとめたら、こちらのissueをclosesしていただいて構いません。
以上よろしくお願いいたします:bow:

**Comment by kerochelo** [comment]
@shimoharuki 
すみませんもう１点追加で:pray:
サービス的にはユーザーがコンテンツを探すことがメインになるので、探しやすくなるように検索機能を作成して、アートコンプリート機能を実装して技術を強くしていくと良さそうです！
下記を参考に実装しておきましょう！
https://github.com/afcapel/stimulus-autocomplete
https://github.com/xpeppers/rails-autocomplete
